return {
  -- disable trouble
  -- { "folke/trouble.nvim", enabled = false },
  -- { "folke/tokyonight.nvim", enabled = false },
  --{ "folke/noice.nvim", enabled = false },
  -- { "catppuccin/nvim", enabled = false },
  { "nvim-pack/nvim-spectre", enabled = false },
  { "lewis6991/gitsigns.nvim", enabled = false },
  -- { "jose-elias-alvarez/null-ls.nvim", enabled = false },
  { "jose-elias-alvarez/none-ls.nvim", enabled = false },
  -- { "rcarriga/nvim-notify", enabled = false },
  { "stevearc/dressing.nvim", enabled = false },
  { "folke/persistence.nvim", enabled = false },
  { "zbirenbaum/copilot.lua", enabled = false },
  { "zbirenbaum/copilot-cmp", enabled = false },
  { "gbprod/yanky.nvim", enabled = false },
  { "kkharji/sqlite.lua", enabled = false },
  -- { "mfussenegger/nvim-dap", enabled = false },
  -- { "rcarriga/nvim-dap-ui", enabled = false },
  -- { "theHamsta/nvim-dap-virtual-text", enabled = false },
  -- { "jay-babu/mason-nvim-dap.nvim", enabled = false },
  { "jbyuki/one-small-step-for-vimkind", enabled = false },
  { "ggandor/flit.nvim", enabled = false },
  { "ggandor/leap.nvim", enabled = false },
  { "tpope/vim-repeat", enabled = false },
  { "echasnovski/mini.files", enabled = false },
  -- { "nvim-neotest/neotest", enabled = false },
}
